;AUTHOR: PRONOY CHOPRA
;WEBSITE: http://www.pronoy.in

.INC "../include/m32def.inc"

;PORTC HAS 8 LEDS
;DELAY REQUIRED

.ORG 0

;STACK POINTER SET
LDI R16, HIGH(RAMEND)
OUT SPH, R16
LDI R16, LOW(RAMEND)
OUT SPL, R16

;MAIN LABEL
MAIN:
LDI R16, 0xFF 
OUT DDRC, R16 ;PORTC IS OUTPUT

BACK:
COM R16 ;COMPLEMENT THE VALUE IN R16
OUT PORTC, R16 ;PUSH THE VALUE IN R16 TO PORTC
CALL DELAY
RJMP BACK ;KEEP DOING THIS INFINITELY

DELAY:
LDI R17, 100
LOOP3: LDI R18, 255
LOOP2: LDI R19, 255
LOOP1: DEC R19 
BRNE LOOP1 ;KEEP DECREASING R19
DEC R18 
BRNE LOOP2 ;FOR EVERY DECREASE OF R18 REDO THE PREVIOUS LOOP
DEC R17 
BRNE LOOP3 ;FOR EVERY DECREASE OF R17 REPEAT PREVIOUS LOOP
RET 	   ;RETURN TO PREVIOUS PC ADDRESS